### ISSUE TITLE
Hardware test for factory and field testing

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-project#10]
In the factory a series of tests has to be executed in order to check that the hardware is fully functional. This document describes the tests executed.

**Phase 0: preparation**
- LCD is attached to the badge
- Switch for enabling the speaker is set to ON position

**Phase 1: flashing the firmware**
- Badge is connected to PC
 (badge shows up as RP2040 bootloader device)
- Flash RP2040 via picotool (or uf2 file)
 (badge shows up as MCH2022 badge with two serial ports)
- Flashing ESP32 via esptool.py (port /dev/ttyACM0)
 (Badge starts firmware)
 
 **Phase 2: Automatic tests**
 (If during any of these tests an error occurs the ESP32 stops and reboots after a delay, this allows the operator to see that something is wrong)
 - [x] ESP32 starts showing status information on the LCD screen > check if LCD is functional
 - [x] ESP32 reads firmware version from RP2040 over I2C, testing I2C bus and RP2040 I2C connection
 - [x] ESP32 puts ICE40 in reset state and checks that it does not signal DONE
 - [x] ESP32 initializes BNO055 sensor
 - [ ] ESP32 initializes BME680 sensor
 - [ ] ESP32 polls RP2040 for button states, all buttons should NOT be pressed
 - [ ] ESP32 tells RP2040 to generate an interrupt, check that it arrives
 - [ ] ESP32 turns on addressable LEDs, showing a static test pattern
 - [ ] ESP32 loads FPGA test bitstream
 (ESP32 releases control over LCD)
  - [ ] FPGA takes control over LCD and shows test pattern / image
 - [ ] FPGA starts showing R, G, B cycle pattern on LED
 - [ ] FPGA sets PMOD lines high, then low one by one
 - [ ] FPGA tests PSRAM
 - [ ] ESP32 writes test data over SPI
 - [ ] FPGA pulls interrupt line low
 - [ ] ESP32 reads test data + PSRAM test result over SPI
 - [ ] After SPI read FPGA releases interrupt line
 - [ ] FPGA echos data sent to the serial port (/dev/ttyACM1) with inverted case
 - [ ] ESP32 tells RP2040 to test the FPGA serial port
 - [ ] ESP32 gets interrupt from RP2040 and reads self test result

**Phase 3: Manual test**
(The FPGA is still showing it's test pattern)
 - [ ] User presses A button
 - [ ] ESP32 puts FPGA in reset state
 - [ ] ESP32 takes control over LCD screen
 - [ ] ESP32 shows button state on LCD so that user can check all buttons
 - [ ] ESP32 tries to mount the SD card and shows SD card state (success/fail) on the screen of the button test
